exp_name: "test_exp"

# Hyperparameters
model_name: "test_cae"
model_args:
  loss_name: "mse" # mse, inter_class_mse, inter_intra_loss
batch_size: 4
eval_batch_size: 100
learning_rate: 0.0005
weight_decay: 0.00001
num_episodes: 100000
rotation_angle: 5    # Angle for data augmentation.
input_size: 128

eval_steps: 20
num_eval_samples: 1000

# Environment configuration
data_dir: "/Users/Tim/data/tcga_luad/gdc_download_20181013_213421.982108"
data_csv: "/Users/Tim/data/tcga_luad/gdc_download_20181013_213421.982108/tile_locations.csv"

tensorboard_dir: "/Users/Tim/dev/cw/honours/tensorboard"
logging_dir: "/Users/Tim/dev/cw/honours/logs"

use_gpu: False

random_seed: 42